### ISSUE TITLE
Fix the decimal separator

### ISSUE THREAD

**Issue by bigleka** [Microsoft/sqlopsstudio#1317]
Version 0.29.1-insider
Commit 8c2d79e9cfcea56f52a81bfd215f50b790fd9223
Date 2018-05-01T06:07:55.597Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Please, fix the decimal separator, now the people are launch new Extensions and we can add more information to "Manage", the problem with using "." (dot) instead of "," (comma) became a really problem.
Just fix using the current user language.

**Comment by bigleka** [comment]
@kburtram maybe November /2022 ?

**Comment by alanrenmsft** [comment]
@bigleka , I am looking into the issue now, would like to make sure we are on the same page, could you please provide more detailed information about the issue with some screenshots?

Thanks
Alan

**Comment by kburtram** [comment]
@bigleka is this issue specific to how the decimal separator is handled in the Manage dashboard with Insights extensions, or is this a more general problem report about decimal separator handling all-up?

If there are a concrete scenarios that are being impacted it will help scope the work required to address this issue.  Thanks!

**Comment by bigleka** [comment]
Hi @alanrenmsft The problem is more a cosmetic issue, in any dashboard if the result came using comma instead of point the graphic not render.
![image](https://user-images.githubusercontent.com/13354954/44033434-c05e96e0-9ee0-11e8-92e5-347778e7b43b.png)

The querys works fine.
![image](https://user-images.githubusercontent.com/13354954/44033465-d871461a-9ee0-11e8-9340-3a71a1acf993.png)

**Comment by alanrenmsft** [comment]
Thanks @bigleka for reporting the issue and providing repro steps, the issue has been fixed, the next release will have the fix.

**Comment by bigleka** [comment]
Hi @alanrenmsft , I download the version 0.32.4-insider and the problem persist.
I do a new installation in other machine and the same problem
![image](https://user-images.githubusercontent.com/13354954/44235593-74aa3e00-a180-11e8-83d3-e9ee1b6bdf6f.png)

**Comment by alanrenmsft** [comment]
@bigleka Would you like to try something to test the changes? you can grab the latest tool service binaries but you will need access to https://github.com/Microsoft/sqltoolsservice/releases. please let me know if you would like to give it a try.

**Comment by bigleka** [comment]
Hi, I download the release 0.32.5-insider and work great.
Thank you, very nice job.
