### ISSUE TITLE
Script as Create doesn't work for stored procedures

### ISSUE THREAD

**Issue by Galaeci** [Microsoft/sqlopsstudio#177]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. Connected to a SQL 2016 database and tried to script a SP from the server browser. It seems to work for most SPs but fails on those that use CREATE OR ALTER PROCEDURE with message: "No script was returned when scripting as created on object Stored Procedure"
2. The following simple script can be used to test this: 
```
CREATE OR ALTER PROCEDURE
AS
SELECT 1

**Comment by erickangMSFT** [comment]
@Galaeci confirmed as a bug.

**Comment by danatcofo** [comment]
#180 opened because my search fu did not find this one till afterwards.   going to close it as dupe.

**Comment by erik-mileiq** [comment]
I get this error for all stored procedures on SQL Data Warehouse.

Version 0.23.6 (0.23.6)
Mac OSX 10.13.1

**Comment by SebastianPfliegel** [comment]
#187 was closed as duplicate. I'm okay with that. Just wanted to mention that the error may be the same, but the cause is sligthly a different one: additional spaces between CREATE/ALTER and PROCEDURE.

**Comment by erickangMSFT** [comment]
@SebastianPfliegel agreed. @llali is looking into the code under the hood and it might be the same code path. For now, let's track both scripting SP for both CREATE and CREATE OR ALTER cases with this issue. If it turns out two different fixes then let's separate it out.

**Comment by llali** [comment]
@SebastianPfliegel you're right. It's a different repro for the same issue. My fix will cover both scenarios and it will be in the next release.

**Comment by llali** [comment]
Fixed in sqltoolservice v1.2.0-alpha.39. It will be in the next release

**Comment by ceymard** [comment]
I still encounter this problem in 0.32.8/linux on CREATE and ALTER

Are there blockers with SQL Server versions ?
