### ISSUE TITLE
Long HTML/XML values displaying expanded over other results in query

### ISSUE THREAD

**Issue by ebernertt** [Microsoft/sqlopsstudio#2086]
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:
1. Table t has a column which is used to store HTML body for email templates
2. Run query against emailBody column, or * on whole table
3. HTML or XML code is not wrapped in column, rather displays expanded across other columns and rows.
![screen shot 2018-07-30 at 3 47 29 pm](https://user-images.githubusercontent.com/31105768/43420483-d5a68fdc-9411-11e8-86bf-8f383cdcceac.png)
![screen shot 2018-07-30 at 3 47 48 pm](https://user-images.githubusercontent.com/31105768/43420484-d5babea8-9411-11e8-9189-922cfa6f6ad9.png)

**Comment by kburtram** [comment]
This should be fixed in the latest `insiders` build at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.2.1. We'll include this fix in the next `stable` build later in August. Please reactive if you still hit the issue with these builds.

**Comment by uniqalex** [comment]
0.32.8
The result set now looks good, but IT IS REALY SO SLOWLY scrolled ((
https://gyazo.com/5b9762711a4d422e290d4d54e7c49a32

But the problem with CHART Viewer is still exists
https://gyazo.com/c63c70740b49aa9c22b60297e8646fc4
![image](https://user-images.githubusercontent.com/22915408/45081511-07932400-b100-11e8-92a1-1c4c2300d1a3.png)
