### ISSUE TITLE
Column header overrun in Agent Jobs grid

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/sqlopsstudio#2118]
Issue Type: <b>Bug</b>

The column headers overrun the filter caret in a narrow window scenario without creating any horizontal scrollbars.

Resizing the window does not cause redraw - the columns remain cramped together.

![image](https://user-images.githubusercontent.com/8250560/43554394-ebfb5752-95a8-11e8-9be7-f701428e0fe7.png)

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (4.31GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.3
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.1
vsliveshare|ms-|0.3.472

</details>

**Comment by kburtram** [comment]
@abist I think the columns should have a minimum to reduce the likelihood this will occur.

**Comment by abist** [comment]
@kburtram We might need to get rid of one of the columns if we want to set a min-width for every column.  We didn't account for the Run Status Graph column earlier, so we should probably have a meeting to discuss this.

**Comment by kburtram** [comment]
@abist let's sync-up to discuss.  I'm not clear why we can't just set a min width on the columns and then let the grid overflow if necessary.  You can enlighten me 😄

**Comment by abist** [comment]
@vickyharp This seems like a pretty old release. This was fixed in the new releases.

**Comment by vickyharp** [comment]
@abist I believe you, but it's still showing up on my machine, so am I missing an update?

**Comment by abist** [comment]
@vickyharp This version as you stated is 0.31.4. The latest insider release right now is 0.32.2 here - https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.2.1. Sorry for the confusion.
